name: Build Docker image

on:
  push:
    branches-ignore:
      - funke  # Covered by docker-push.yml
  pull_request:

jobs:
  build:

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: read  # To read NPM registry

    uses: gunet/funke-wallet-ecosystem/.github/workflows/docker-build-push.yml@master
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/funke-wallet-backend-server:latest
      docker-push: false
      dockerfile-path: ./Dockerfile
